### ISSUE TITLE
Error after the last step of README.md

### ISSUE THREAD

**Issue by sdadoun** [Thinkmill/keystone-forgotten-password#7]
Hello, 

I installed keystoneJS and keystone-forgotten-password, but à the last step (the steps before are ok) of README.md when, in the routes/index.js, I add :

`app.use('/profile', middleware.authenticated, updatePassword());
`

I got this error :

```
$ node keystone.js
----------------------------------------
WARNING: MISSING MAILGUN CREDENTIALS
----------------------------------------
You have opted into email sending but have not provided
mailgun credentials. Attempts to send will fail.

Create a mailgun account and add the credentials to the .env file to
set up your mailgun integration
TypeError: Cannot read property 'length' of undefined
    at pathtoRegexp (/home/simon/tks3/node_modules/path-to-regexp/index.js:63:48)
    at new Layer (/home/simon/tks3/node_modules/express/lib/router/layer.js:45:17)
    at Function.use (/home/simon/tks3/node_modules/express/lib/router/index.js:464:17)
...
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

Any idea ?
Thanks

**Comment by laurenskling** [comment]
This looks like you've been using this with Keystone 3 not 4
